In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("AI_Job_Market_Raw.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'AI_Job_Market_Raw.xlsx'

In [ ]:
df.head()

,Job_ID,Job_Title,Company,Location,Country,Experience_Level,Employment_Type,Work_Mode,Salary_Min,Salary_Max,...,PyTorch,AWS,Azure,GCP,Statistics,NLP,Generative_AI,Years_Experience,Education,Job_Description
0,JOB11909,Data Scientist,Siemens,Pune,India,Mid Level,Full Time,On-site,890000,1250000,...,No,Yes,No,No,Yes,No,No,2,Master's,Seeking a Data Scientist to support Technology...
1,JOB11640,AI/ML Intern,Infosys,Delhi,Australia,Senior,Full Time,Remote,350000,490000,...,No,Yes,No,No,Yes,No,No,7,Bachelor's,Seeking a AI/ML Intern to support Finance proj...
2,JOB11057,BI Analyst,Amazon,Bangalore,India,Senior,Full Time,Remote,680000,890000,...,No,No,No,Yes,No,No,Yes,9,Bachelor's,Seeking a BI Analyst to support IT Services pr...
3,JOB10488,Data Scientist,Bosch,Noida,India,Entry Level,Full Time,Hybrid,760000,1030000,...,No,No,Yes,No,Yes,No,No,1,Bachelor's,Seeking a Data Scientist to support Finance pr...
4,JOB11229,NLP Engineer,Deloitte,Delhi,India,Mid Level,Full Time,Remote,1000000,1390000,...,No,No,No,No,Yes,No,No,5,Master's,Seeking a NLP Engineer to support E-commerce p...

In [ ]:
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])

Rows: 2020
Columns: 32

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 32 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Job_ID            2020 non-null   object
 1   Job_Title         2020 non-null   object
 2   Company           2020 non-null   object
 3   Location          2020 non-null   object
 4   Country           2020 non-null   object
 5   Experience_Level  2020 non-null   object
 6   Employment_Type   2020 non-null   object
 7   Work_Mode         2020 non-null   object
 8   Salary_Min        2020 non-null   int64
 9   Salary_Max        2020 non-null   int64
 10  Salary_Currency   2020 non-null   object
 11  Posted_Date       2020 non-null   datetime64[ns]
 12  Industry          2020 non-null   object
 13  Company_Size      2002 non-null   object
 14  Python            2020 non-null   object
 15  SQL               2020 non-null   object
 16  Power_BI          2002 non-null   object
 17  Excel             2020 non-null   object
 18  Tableau           2002 non-null   object
 19  Machine_Learning  2020 non-null   object
 20  Deep_Learning     2020 non-null   object
 21  TensorFlow        2020 non-null   object
 22  PyTorch           2020 non-null   object
 23  AWS               2002 non-null   object
 24  Azure             2020 non-null   object
 25  GCP               2020 non-null   object
 26  Statistics        2020 non-null   object
 27  NLP               2020 non-null   object
 28  Generative_AI     2020 non-null   object
 29  Years_Experience  2020 non-null   int64
 30  Education         2002 non-null   object
 31  Job_Description   2020 non-null   object
dtypes: datetime64[ns](1), int64(3), object(28)
memory usage: 505.1+ KB

In [ ]:
df.isnull().sum()
#used to check missing values

Job_ID               0
Job_Title            0
Company              0
Location             0
Country              0
Experience_Level     0
Employment_Type      0
Work_Mode            0
Salary_Min           0
Salary_Max           0
Salary_Currency      0
Posted_Date          0
Industry             0
Company_Size        18
Python               0
SQL                  0
Power_BI            18
Excel                0
Tableau             18
Machine_Learning     0
Deep_Learning        0
TensorFlow           0
PyTorch              0
AWS                 18
Azure                0
GCP                  0
Statistics           0
NLP                  0
Generative_AI        0
Years_Experience     0
Education           18
Job_Description      0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(20)

In [ ]:
df = df.duplicated()
print("Rows after removing duplicates :",len(df))

Rows after removing duplicates : 2020

In [ ]:
df.columns

Index(['Job_ID', 'Job_Title', 'Company', 'Location', 'Country',
       'Experience_Level', 'Employment_Type', 'Work_Mode', 'Salary_Min',
       'Salary_Max', 'Salary_Currency', 'Posted_Date', 'Industry',
       'Company_Size', 'Python', 'SQL', 'Power_BI', 'Excel', 'Tableau',
       'Machine_Learning', 'Deep_Learning', 'TensorFlow', 'PyTorch', 'AWS',
       'Azure', 'GCP', 'Statistics', 'NLP', 'Generative_AI',
       'Years_Experience', 'Education', 'Job_Description'],
      dtype='object')

In [ ]:
df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
)

df.columns

Index(['Job_ID', 'Job_Title', 'Company', 'Location', 'Country',
       'Experience_Level', 'Employment_Type', 'Work_Mode', 'Salary_Min',
       'Salary_Max', 'Salary_Currency', 'Posted_Date', 'Industry',
       'Company_Size', 'Python', 'SQL', 'Power_BI', 'Excel', 'Tableau',
       'Machine_Learning', 'Deep_Learning', 'TensorFlow', 'PyTorch', 'AWS',
       'Azure', 'GCP', 'Statistics', 'NLP', 'Generative_AI',
       'Years_Experience', 'Education', 'Job_Description'],
      dtype='object')

In [ ]:
text_columns = [
    "Job_Title",
    "Company",
    "Location",
    "Country",
    "Experience_Level",
    "Employment_Type",
    "Work_Mode",
    "Salary_Currency",
    "Industry",
    "Company_Size",
    "Education"
]

for col in text_columns:
    df[col] = df[col].astype("string").str.strip().str.title()

In [ ]:
df["Job_Title"].value_counts()

Job_Title
Data Analyst                 464
Data Scientist               272
Data Engineer                221
Machine Learning Engineer    220
Ai Engineer                  196
Bi Analyst                   179
Ml Engineer                  159
Business Analyst             129
Ai/Ml Intern                  94
Nlp Engineer                  86
Name: count, dtype: Int64

In [ ]:
df.isnull().sum()

Job_ID               0
Job_Title            0
Company              0
Location             0
Country              0
Experience_Level     0
Employment_Type      0
Work_Mode            0
Salary_Min           0
Salary_Max           0
Salary_Currency      0
Posted_Date          0
Industry             0
Company_Size        18
Python               0
SQL                  0
Power_BI            18
Excel                0
Tableau             18
Machine_Learning     0
Deep_Learning        0
TensorFlow           0
PyTorch              0
AWS                 18
Azure                0
GCP                  0
Statistics           0
NLP                  0
Generative_AI        0
Years_Experience     0
Education           18
Job_Description      0
dtype: int64

In [ ]:
categorical_columns = [
    "Power_BI",
    "Tableau",
    "AWS",
    "Education",
    "Company_Size"
]

for col in categorical_columns:
    df[col] = df[col].fillna("unknown")

In [ ]:
df[["Salary_Min","Salary_Max","Years_Experience"]].dtypes

Salary_Min          int64
Salary_Max          int64
Years_Experience    int64
dtype: object

In [ ]:
numeric_columns = [
    "Salary_Min",
    "Salary_Max",
    "Years_Experience"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [ ]:
df["Posted_Date"] = pd.to_datetime(
    df["Posted_Date"],
    errors="coerce"
)

In [ ]:
df["Posted_Date"].dtype

dtype('<M8[ns]')

In [ ]:
df["Average_Salary"] = (
    df["Salary_Min"] + df["Salary_Max"]
) / 2

In [ ]:
df[[
    "Job_Title",
    "Salary_Min",
    "Salary_Max",
    "Average_Salary"
]].head()

        Job_Title  Salary_Min  Salary_Max  Average_Salary
0  Data Scientist      890000     1250000       1070000.0
1    Ai/Ml Intern      350000      490000        420000.0
2      Bi Analyst      680000      890000        785000.0
3  Data Scientist      760000     1030000        895000.0
4    Nlp Engineer     1000000     1390000       1195000.0

In [ ]:
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])

Rows: 2020
Columns: 33

In [ ]:
df.isnull().sum()

Job_ID              0
Job_Title           0
Company             0
Location            0
Country             0
Experience_Level    0
Employment_Type     0
Work_Mode           0
Salary_Min          0
Salary_Max          0
Salary_Currency     0
Posted_Date         0
Industry            0
Company_Size        0
Python              0
SQL                 0
Power_BI            0
Excel               0
Tableau             0
Machine_Learning    0
Deep_Learning       0
TensorFlow          0
PyTorch             0
AWS                 0
Azure               0
GCP                 0
Statistics          0
NLP                 0
Generative_AI       0
Years_Experience    0
Education           0
Job_Description     0
Average_Salary      0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(20)

In [ ]:
df.head()

,Job_ID,Job_Title,Company,Location,Country,Experience_Level,Employment_Type,Work_Mode,Salary_Min,Salary_Max,...,AWS,Azure,GCP,Statistics,NLP,Generative_AI,Years_Experience,Education,Job_Description,Average_Salary
0,JOB11909,Data Scientist,Siemens,Pune,India,Mid Level,Full Time,On-Site,890000,1250000,...,Yes,No,No,Yes,No,No,2,Master'S,Seeking a Data Scientist to support Technology...,1070000.0
1,JOB11640,Ai/Ml Intern,Infosys,Delhi,Australia,Senior,Full Time,Remote,350000,490000,...,Yes,No,No,Yes,No,No,7,Bachelor'S,Seeking a AI/ML Intern to support Finance proj...,420000.0
2,JOB11057,Bi Analyst,Amazon,Bangalore,India,Senior,Full Time,Remote,680000,890000,...,No,No,Yes,No,No,Yes,9,Bachelor'S,Seeking a BI Analyst to support IT Services pr...,785000.0
3,JOB10488,Data Scientist,Bosch,Noida,India,Entry Level,Full Time,Hybrid,760000,1030000,...,No,Yes,No,Yes,No,No,1,Bachelor'S,Seeking a Data Scientist to support Finance pr...,895000.0
4,JOB11229,Nlp Engineer,Deloitte,Delhi,India,Mid Level,Full Time,Remote,1000000,1390000,...,No,No,No,Yes,No,No,5,Master'S,Seeking a NLP Engineer to support E-commerce p...,1195000.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Job_ID            2020 non-null   object
 1   Job_Title         2020 non-null   string
 2   Company           2020 non-null   string
 3   Location          2020 non-null   string
 4   Country           2020 non-null   string
 5   Experience_Level  2020 non-null   string
 6   Employment_Type   2020 non-null   string
 7   Work_Mode         2020 non-null   string
 8   Salary_Min        2020 non-null   int64
 9   Salary_Max        2020 non-null   int64
 10  Salary_Currency   2020 non-null   string
 11  Posted_Date       2020 non-null   datetime64[ns]
 12  Industry          2020 non-null   string
 13  Company_Size      2020 non-null   string
 14  Python            2020 non-null   object
 15  SQL               2020 non-null   object
 16  Power_BI          2020 non-null   object
 17  Excel             2020 non-null   object
 18  Tableau           2020 non-null   object
 19  Machine_Learning  2020 non-null   object
 20  Deep_Learning     2020 non-null   object
 21  TensorFlow        2020 non-null   object
 22  PyTorch           2020 non-null   object
 23  AWS               2020 non-null   object
 24  Azure             2020 non-null   object
 25  GCP               2020 non-null   object
 26  Statistics        2020 non-null   object
 27  NLP               2020 non-null   object
 28  Generative_AI     2020 non-null   object
 29  Years_Experience  2020 non-null   int64
 30  Education         2020 non-null   string
 31  Job_Description   2020 non-null   object
 32  Average_Salary    2020 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(17), string(11)
memory usage: 520.9+ KB

In [ ]:
df.describe()

,Salary_Min,Salary_Max,Posted_Date,Years_Experience,Average_Salary
count,2.020000e+03,2.020000e+03,2020,2020.000000,2.020000e+03
mean,7.748614e+05,1.018059e+06,2025-10-24 00:29:13.663366144,3.934653,8.964604e+05
min,1.500000e+05,2.500000e+05,2025-01-01 00:00:00,0.000000,2.000000e+05
25%,5.700000e+05,7.300000e+05,2025-06-06 00:00:00,1.000000,6.500000e+05
50%,7.500000e+05,1.000000e+06,2025-10-22 12:00:00,3.000000,8.750000e+05
75%,9.500000e+05,1.270000e+06,2026-03-15 00:00:00,5.000000,1.106250e+06
max,1.830000e+06,2.250000e+06,2026-08-10 00:00:00,15.000000,2.025000e+06
std,2.848494e+05,3.518040e+05,NaN,3.197586,3.166593e+05

In [ ]:
df.to_excel(
    "AI_Job_Market_Cleaned.xlsx",
    index=False
)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!

In [ ]:
df.info()

NameError: name 'df' is not defined